apiVersion: v1
kind: Service
metadata:
  name: spring-kubernetes-example
spec:
  selector:
    app: spring-kubernetes-example
  type: NodePort
  ports:
  - name: spring-kubernetes-example-port
    port:  8080
